---
-  name: Install Apache2 and PHP on web server
   hosts: web
   become: true
   become_method: sudo
   tasks:
           -  name: Install Apache2
              apt:
                   name: apache2
                   state: present
           -  name: Install PHP
              apt:
                   name: libapache2-mod-php
                   state: present

-  name: Start Apache2 on webserver
   hosts: web
   become: true
   become_method: sudo
   tasks:
           -  name: Start Apache2 on webserver
              service:
                   name: apache2
                   state: started

-  name: Change timezone on webserver
   hosts: web
   become: true
   become_method: sudo
   tasks:
           -  name: Set timezone to Africa/Lagos
              timezone:
                   name: Africa/Lagos

-  name: Copy index.php file to webserver
   hosts: web
   become: true
   become_method: sudo
   tasks:
           -  name: copying file with playbook
              copy:
                   src: ~/ansible/index.php
                   dest: /var/www/html/index.php
                   mode: 0775

-  name: Restart web server
   hosts: web
   become: true
   become_method: sudo
   tasks:
           -  name: Restart Apache
              service:
                   name: apache2
                   state: restarted
                                            